// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF-y1O_4bnGX6cpasP0yeNMx7qXqeIL60',
    appId: '1:829516799814:web:f8a5c9f661ff0f80e88f47',
    messagingSenderId: '829516799814',
    projectId: 'quoridor-290f6',
    authDomain: 'quoridor-290f6.firebaseapp.com',
    storageBucket: 'quoridor-290f6.firebasestorage.app',
    measurementId: 'G-JC589G17CQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt67wUePyZdiEZUMeaVNAnTEFR9_i1_pM',
    appId: '1:829516799814:android:34b8ce29b4e71c12e88f47',
    messagingSenderId: '829516799814',
    projectId: 'quoridor-290f6',
    storageBucket: 'quoridor-290f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByIDYkwQaFGIN_qJTYlcOzzMvwPKrZ5cM',
    appId: '1:829516799814:ios:5f3bb5449481d145e88f47',
    messagingSenderId: '829516799814',
    projectId: 'quoridor-290f6',
    storageBucket: 'quoridor-290f6.firebasestorage.app',
    iosBundleId: 'com.MoReH.quoridor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByIDYkwQaFGIN_qJTYlcOzzMvwPKrZ5cM',
    appId: '1:829516799814:ios:5f3bb5449481d145e88f47',
    messagingSenderId: '829516799814',
    projectId: 'quoridor-290f6',
    storageBucket: 'quoridor-290f6.firebasestorage.app',
    iosBundleId: 'com.MoReH.quoridor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF-y1O_4bnGX6cpasP0yeNMx7qXqeIL60',
    appId: '1:829516799814:web:8b6ce39c28540e27e88f47',
    messagingSenderId: '829516799814',
    projectId: 'quoridor-290f6',
    authDomain: 'quoridor-290f6.firebaseapp.com',
    storageBucket: 'quoridor-290f6.firebasestorage.app',
    measurementId: 'G-7ZL3R161LV',
  );
}
